---
sidebar: sidebar 
permalink: faq-cloud-tiering.html 
keywords: faq, questions, requirements, service connector, object store, object storage, aws, azure, bucket, cluster, aggregate, s3, storage class, standard, inactive data reporting, auto, volume tiering policy, policy, tiering policy, snapshot, cold, inactive, infrequent 
summary: この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。 
---
= Cloud Tiering Technical FAQ 』を参照してください
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。



== Cloud Tiering Service の略

Cloud Tieringの仕組みについては、次のFAQを参照してください。



=== Cloud Tieringサービスを使用するメリットは何ですか？

Cloud Tieringは、データの急増に伴う課題に対応し、次のようなメリットを提供します。

* クラウドへのデータセンターを容易に拡張できるため、最大50倍のスペースを確保できます
* ストレージの最適化により、ストレージを平均70%削減
* 総所有コストを平均30%削減
* アプリケーションをリファクタリングする必要はありません




=== クラウドへの階層化にはどのようなデータが役立ちますか？

基本的に、プライマリストレージシステムとセカンダリストレージシステムの両方でアクセス頻度の低いデータがあれば、クラウドへの移行のターゲットとして適しています。プライマリシステムでは、このようなデータには、スナップショット、履歴レコード、および完了したプロジェクトが含まれます。セカンダリシステムでは、DRとバックアップ用に作成されたプライマリデータのコピーを含むすべてのボリュームが対象となります。



=== NASボリュームとSANボリュームの両方からデータを階層化できますか。

はい。NASボリュームからパブリッククラウドまたはStorageGRID などのプライベートクラウドにデータを階層化できます。SANプロトコルでアクセスされるデータを階層化する場合、SANプロトコルはNASよりも接続の問題の影響を受けやすいため、プライベートクラウドを使用することを推奨します。



=== アクセス頻度の低いデータや使用頻度の低いデータの定義とは何ですか？また、それらをどのように制御するのですか？

コールドデータと呼ばれることもあるのは、「一定の時間アクセスされなかったボリュームブロック（メタデータを除く）」です。「時間」は、cooling-daysという名前の階層化ポリシー属性によって決まります。



=== Cloud Tieringを使用すると、ストレージ効率化による削減効果をクラウド階層に維持できますか。

はい。データをクラウド階層に移動するときに、圧縮、重複排除、コンパクションなどのONTAP のボリュームレベルのストレージ効率化機能が維持されます。



=== FabricPool とクラウド階層化の違いは何ですか？

FabricPool は、ONTAP CLIとSystem Managerを使用して自己管理することも、クラウド階層化を使用してサービスとして管理することもできる、ONTAPの階層化テクノロジです。Cloud Tieringを使用すると、FabricPool は、ONTAP とクラウドの両方で高度な自動化プロセスを使用したマネージドサービスに変わり、ハイブリッドクラウドとマルチクラウドの両方の環境における階層化の可視性と制御性が向上します。



=== データをクラウドに階層化してディザスタリカバリやバックアップ/アーカイブに使用できますか。

いいえボリュームのメタデータはパフォーマンス階層から階層化されることはないため、オブジェクトストレージに格納されているデータに直接アクセスすることはできません。

ただし、Cloud Tieringを使用すると、セカンダリシステムとSnapMirrorデスティネーションボリューム（DPボリューム）にデータを階層化し、データセンターの設置面積とTCOを削減することで、対費用効果の高いバックアップとDRを実現できます。



=== Cloud Tieringは、ボリュームレベルまたはアグリゲートレベルで適用されていますか。

クラウド階層化は、各ボリュームに階層化ポリシーを関連付けることでボリュームレベルで有効になります。コールドデータはブロックレベルで識別されます。



=== クラウド階層化は、どのブロックをクラウドに階層化するかをどのようにして決定しますか？

ボリュームに関連付けられている階層化ポリシーは、どのブロックをいつ階層化するかを制御するメカニズムです。ポリシーでは、データブロックのタイプ（スナップショット、ユーザデータ、またはその両方）とクーリング期間を定義します。を参照してください link:concept-cloud-tiering.html#volume-tiering-policies["ボリューム階層化ポリシー"] を参照してください。



=== Cloud Tieringは、ボリュームの容量にどのような影響を及ぼしますか？

Cloud Tieringは、ボリュームの容量には影響しませんが、アグリゲートのパフォーマンス階層の使用率には影響しません。



=== クラウドの階層化でInactive Data Reportingは有効になりますか。

はい、Cloud Tieringを使用すると、各アグリゲートでInactive Data Reporting（IDR）を有効にできます。この設定により、アクセス頻度の低いデータのうち、低コストのオブジェクトストレージに階層化できるデータの量を特定できます。



=== IDRを実行してからどのくらいの時間で情報を確認できますか？

IDRは、設定されたクーリング期間が経過したあとに情報の表示を開始します。ONTAP 9.7以前を使用した場合、IDRのクーリング期間は調整できず、31日間でした。ONTAP 9.8以降では、IDRのクーリング期間を最大183日に設定できます。



== ライセンスとコスト

Cloud Tieringを使用するためのライセンスとコストに関するFAQを次に示します。



=== Cloud Tieringのコストはいくらですか？

コールドデータをパブリッククラウドに階層化する場合：

* 従量課金制（PAYGO）の場合、使用量に基づくサブスクリプション：GBあたり月額$0.05
* 年単位（BYOL）のタームベースサブスクリプション：GBあたり0.033ドル/月から


コールドデータをNetApp StorageGRID システム（プライベートクラウド）に階層化しても、コストはかかりません。



=== 同じONTAP クラスタにBYOLライセンスとPAYGOライセンスの両方を利用できますか。

はい。Cloud Tieringを使用すると、BYOLライセンス、PAYGOサブスクリプション、またはその両方を組み合わせて使用できます。



=== BYOLの容量制限に達した場合はどうなりますか？

BYOLの容量制限に達すると、新しいコールドデータの階層化が停止し、それまで階層化されていたすべてのデータにアクセスできる状態になります。PAYGOマーケットプレイスで_ Cloud Manager - Deploy & Manage Cloud Data Services _を利用している場合、新しいコールドデータは引き続きオブジェクトストレージに階層化され、使用量に応じて料金が発生します。



=== Cloud Tieringライセンスには、クラウドプロバイダからの出力料金が含まれていますか。

いいえ、できません。



=== オンプレミスシステムのリハイドレーションは、クラウドプロバイダが負担する出力コストの影響を受けますか。

はい。パブリッククラウドからの読み取りはすべて出力料金の対象となります。



=== クラウドの料金を見積もる方法Cloud Tieringには、「What if」モードがありますか。

クラウドプロバイダがデータをホストするためにどの程度の料金を請求するかを見積もる最良の方法は、計算ツールを使用することです。 https://calculator.aws/#/["AWS"]、 https://azure.microsoft.com/en-us/pricing/calculator/["Azure"] および https://cloud.google.com/products/calculator["Google Cloud"]。



=== オブジェクトストレージからオンプレミスストレージへのデータの読み取り/読み出しに関して、クラウドプロバイダは追加料金を請求していますか？

はい。チェックしてください https://aws.amazon.com/s3/pricing/["Amazon S3の価格設定"]、 https://azure.microsoft.com/en-us/pricing/details/storage/blobs/["Block BLOBの価格設定"]および https://cloud.google.com/storage/pricing["クラウドストレージの価格設定"] データの読み取り/取得に伴う追加の価格設定については、を参照してください。



=== Cloud Tieringを有効にする前に、ボリュームの削減量を見積もり、コールドデータレポートを取得するにはどうすればよいですか。

概算見積書を入手するには、ONTAP クラスタをCloud Managerに追加し、階層化タブにあるCloud Tiering Cluster Dashboardから確認します。Inactive Data Reporting（IDR）が無効になっているか、十分な期間アクティブ化されていない場合、Cloud Tieringは、業界定数の70%を使用して削減量を計算します。IDRデータを利用できるようになると、Cloud Tieringがコスト削減効果を正確な数値に更新します。



== ONTAP

ONTAP に関連する質問を次に示します。



=== Cloud TieringがサポートしているONTAP のバージョンはどれですか？

Cloud Tieringは、ONTAP バージョン9.2以降をサポートしています。



=== どのような種類の ONTAP システムがサポートされていますか。

クラウド階層化は、シングルノードクラスタとハイアベイラビリティAFF 、FAS クラスタ、ONTAP Select クラスタでサポートされています。

FabricPool ミラー構成のクラスタもサポートされますが、階層化設定の実行にはSystem ManagerまたはONTAP CLIを使用する必要があります。



=== HDDのみを使用するFAS システムからデータを階層化できますか。

はい。ONTAP 9.8以降では、HDDアグリゲートでホストされているボリュームからデータを階層化できます。



=== HDDを使用するFAS ノードがあるクラスタに参加しているAFF からデータを階層化できますか。

はい。Cloud Tieringは、任意のアグリゲートでホストされたボリュームを階層化するように設定できます。データ階層化設定は、使用するコントローラの種類や、クラスタが異機種混在であるかどうかに関係なく使用されます。



=== Cloud Volumes ONTAP について教えてください。

Cloud Volumes ONTAP システムを使用している場合は、Cloud Tiering Cluster Dashboardにアクセスして、ハイブリッドクラウドインフラにおけるデータの階層化を最大限に確認できます。ただし、Cloud Volumes ONTAP システムはCloud Tieringから読み取り専用です。Cloud Volumes ONTAP では、クラウド階層化からデータ階層化を設定することはできません。 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-tiering.html["Cloud Volumes ONTAP の階層化はで設定します Cloud Manager の作業環境"^]。



=== 使用しているONTAP クラスタに必要なその他の要件は何ですか。

コールドデータの階層化先によって異なります。詳細については、次のリンクを参照してください。

* link:task-tiering-onprem-aws.html#preparing-your-ontap-clusters["Amazon S3へのデータの階層化"]
* link:task-tiering-onprem-azure.html#preparing-your-ontap-clusters["Azure BLOBストレージへのデータの階層化"]
* link:task-tiering-onprem-gcp.html#preparing-your-ontap-clusters["Google Cloud Storageへのデータの階層化"]
* link:task-tiering-onprem-storagegrid.html#preparing-your-ontap-clusters["データをStorageGRID に階層化する"]
* link:task-tiering-onprem-s3-compat.html#preparing-your-ontap-clusters["データをS3オブジェクトストレージに階層化する"]




== オブジェクトストレージ

オブジェクトストレージに関連する質問を次に示します。



=== サポートされているオブジェクトストレージプロバイダを教えてください。

Cloud Tieringは、次のオブジェクトストレージプロバイダをサポートしています。

* Amazon S3
* Microsoft Azure Blob
* Google クラウドストレージ
* NetApp StorageGRID
* S3 互換オブジェクトストレージ
* IBM Cloud Object Storage（FabricPool の設定はSystem ManagerまたはONTAP CLIを使用して実行する必要があります）




=== 独自のバケット / コンテナを使用できますか。

はい、できます。データの階層化を設定するときに、新しいバケット / コンテナを追加するか、既存のバケット / コンテナを選択するかを選択できます。



=== サポートされているリージョンはどれですか。

* link:reference-aws-support.html["サポートされている AWS リージョン"]
* link:reference-azure-support.html["サポートされている Azure リージョン"]
* link:reference-google-support.html["サポートされている Google Cloud リージョン"]




=== サポートされている S3 ストレージクラスはどれですか？

クラウド階層化では、 _Standard_,_Standard-Infrequent Access_,_one Zone - Infrequent Access_, _Intelligent Tiering _ 、および _Glacier Instant Retrieval_storage の各クラスへのデータ階層化がサポートされています。を参照してください link:reference-aws-support.html["サポートされている S3 ストレージクラス"] 詳細：



=== Amazon S3 Glacier FlexibleおよびS3 Glacier Deep Archiveがクラウド階層化でサポートされていないのはなぜですか。

Amazon S3 Glacier FlexibleおよびS3 Glacier Deep Archiveがサポートされていない主な理由は、クラウド階層化がハイパフォーマンスな階層化解決策 として設計されているため、データを継続的に利用してすばやくアクセスし、読み出しできるようにする必要があるためです。S3 Glacier FlexibleおよびS3 Glacier Deep Archiveでは、データ読み出しが数分から48時間の間の任意の場所に格納されます。



=== WasabiなどのS3互換のオブジェクトストレージサービスをCloud Tieringとともに使用できますか。

はい。ONTAP 9.8以降を使用しているクラスタでは、階層化UIからS3互換オブジェクトストレージを設定できます。 link:task-tiering-onprem-s3-compat.html["詳細はこちらをご覧ください"]。



=== サポートされている Azure Blob アクセス階層はどれですか？

Cloud Tiering は、アクセス頻度の低いデータに対するホットアクセス階層へのデータ階層化をサポートします。を参照してください link:reference-azure-support.html["サポートされる Azure Blob アクセス階層"] 詳細：



=== Google Cloud Storage ではどのストレージクラスがサポートされていますか。

Cloud Tiering は、 _Standard_、 _Nearline _ 、 _Coldline_、 および _Archive_storage の各クラスへのデータ階層化をサポートしています。を参照してください link:reference-google-support.html["サポートされている Google Cloud ストレージクラス"] 詳細：



=== Cloud Tieringは、ライフサイクル管理ポリシーの使用をサポートしていますか。

はい。ライフサイクル管理を有効にすると、 Cloud Tiering でデータをデフォルトのストレージクラス / アクセス階層から、一定期間後にコスト効率の高い階層に移行できます。ライフサイクルルールは、選択したバケット内の Amazon S3 および Google Cloud ストレージのすべてのオブジェクト、および選択したストレージアカウント内の Azure Blob に対応するすべてのコンテナに適用されます。



=== Cloud Tiering は、クラスタ全体に 1 つのオブジェクトストアを使用していますか、それともアグリゲートごとに 1 つ使用していますか

クラスタ全体で 1 つのオブジェクトストアを使用します。



=== 同じアグリゲートに複数のバケットを接続できますか。

ミラーリングの目的で、アグリゲートごとに最大2つのバケットを接続できます。コールドデータは両方のバケットに同期的に階層化されます。バケットは、プロバイダや場所によって異なる場合があります。ただし、Cloud Tiering UIを使用した設定は現在サポートされていません。セットアップはSystem ManagerまたはCLIを使用して実行できます。



=== 同じクラスタ内の複数のアグリゲートに異なるバケットを接続できますか。

はい。一般的なベストプラクティスとして、1つのバケットを複数のアグリゲートに接続することを推奨します。ただし、パブリッククラウドを使用する場合は、オブジェクトストレージサービスのIOPSが最大であるため、複数のバケットを考慮する必要があります。ただし、Cloud Tiering UIを使用した設定は現在サポートされていません。セットアップはSystem ManagerまたはCLIを使用して実行できます。



=== ボリュームをクラスタ間で移行すると、階層化データはどうなりますか。

ボリュームをクラスタ間で移行すると、コールドデータはすべてクラウド階層から読み取られます。デスティネーションクラスタ上の書き込み場所は、階層化が有効になっているかどうか、およびソースボリュームとデスティネーションボリュームで使用されている階層化ポリシーのタイプによって異なります。



=== 同じクラスタ内のノード間でボリュームを移動すると、階層化データはどうなりますか？

デスティネーションアグリゲートにクラウド階層が接続されていない場合、データはソースアグリゲートのクラウド階層から読み取られ、デスティネーションアグリゲートのローカル階層に完全に書き込まれます。デスティネーションアグリゲートにクラウド階層が接続されている場合、データはソースアグリゲートのクラウド階層から読み取られ、最初にデスティネーションアグリゲートのローカル階層に書き込まれます。これにより、迅速なカットオーバーが可能になります。その後、使用された階層化ポリシーに基づいてクラウド階層に書き込まれます。

ONTAP 9.6以降では、デスティネーションアグリゲートがソースアグリゲートと同じクラウド階層を使用している場合、コールドデータはローカル階層に戻されません。



=== 階層化したデータをオンプレミスからパフォーマンス階層に戻すにはどうすればよいですか？

ライトバックは通常、読み取り時に実行され、階層化ポリシーのタイプによって異なります。ONTAP 9.8より前のバージョンでは、_volume move_operationを使用して、ボリューム全体の書き込みを行うことができます。ONTAP 9.8以降、階層化UIには、すべてのデータを*戻すオプションやアクティブファイルシステムを戻すオプションがあります。 link:task-managing-tiering.html#migrating-data-from-the-cloud-tier-back-to-the-performance-tier["データを高パフォーマンス階層に戻す方法をご覧ください"]。



=== 既存のAFF / FASコントローラを新しいコントローラに交換する場合、階層化データをオンプレミスに戻すことはできますか。

いいえ「ヘッド交換」手順 で変更されるのは、アグリゲートの所有権だけです。この場合、データを移動することなく新しいコントローラに変更されます。



=== ディザスタリカバリのシナリオで、階層化されたデータを使用してボリュームまたはシステムをリカバリできますか。

いいえボリュームのメタデータは常にローカルのパフォーマンス階層に格納されるため、災害が発生してローカル階層が失われると、メタデータも失われ、階層化されたデータを参照する方法もありません。



=== クラウドプロバイダのコンソールまたはオブジェクトストレージエクスプローラを使用して、バケットに階層化されたデータを確認できますか。オブジェクトストレージに格納されているデータをONTAP なしで直接使用できますか。

いいえクラウドに対して構築、階層化されたオブジェクトには、単一のファイルは含まれず、複数のファイルから最大1、024個の4KBブロックが含まれます。ボリュームのメタデータは常にローカル階層に残ります。



== コネクタ

Cloud Manager Connectorに関連する質問を次に示します。



=== コネクタは何ですか？

Connectorは、クラウドアカウント内またはオンプレミスでコンピューティングインスタンス上で実行されるソフトウェアで、Cloud Managerによるクラウドリソースのセキュアな管理を可能にします。Cloud Tieringサービスを使用するには、Connectorを導入する必要があります。



=== コネクタはどこに取り付ける必要がありますか？

* データを S3 に階層化する場合、コネクタは AWS VPC またはオンプレミスに配置できます。
* BLOB ストレージにデータを階層化する場合、コネクタは Azure VNet または自社運用環境に配置できます。
* データを Google Cloud Storage に階層化する場合、 Connector は Google Cloud Platform VPC 内に存在する必要があります。
* StorageGRID やその他の S3 互換ストレージプロバイダにデータを階層化する場合は、 Connector をオンプレミスに配置する必要があります。




=== コネクタをオンプレミスに導入できますか。

はい。Connectorソフトウェアは、ネットワーク上のLinuxホストにダウンロードして手動でインストールできます。 https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-installing-linux.html["コネクタをオンプレミスに取り付ける方法については、を参照してください"]。



=== Cloud Tieringを使用するには、クラウドサービスプロバイダを利用するアカウントが必要ですか？

はい。使用するオブジェクトストレージを定義するには、アカウントが必要です。VPCまたはVNet上のクラウドでコネクタを設定する際には、クラウドストレージプロバイダのアカウントも必要です。



=== コネクタに障害が発生した場合の意味は何ですか？

コネクタに障害が発生した場合は、階層化された環境の表示のみが影響を受けます。すべてのデータにアクセスでき、新たに特定されたコールドデータはオブジェクトストレージに自動的に階層化されます。



== 階層化ポリシー



=== 使用可能な階層化ポリシー

次の4つの階層化ポリシーがあります。

●なし：すべてのデータを常時ホットに分類し、ボリュームからオブジェクトストレージにデータを移動できないようにします。●コールドスナップショット（Snapshotのみ）：コールドスナップショットブロックのみがオブジェクトストレージに移動されます。●コールドユーザデータとスナップショット（自動）：コールドスナップショットブロックとコールドユーザデータブロックの両方をオブジェクトストレージに移動します。●すべてのユーザデータ（ALL）：すべてのデータをコールドとして分類し、ボリューム全体をオブジェクトストレージにただちに移動します。

link:concept-cloud-tiering.html#volume-tiering-policies["階層化ポリシーの詳細については、こちらをご覧ください"]。



=== データがコールドと見なされるのはどの時点ですか？

データの階層化はブロックレベルで行われるため、データブロックは一定期間アクセスされていないとコールドとみなされます。この期間は、階層化ポリシーのminimum-cooling-days属性によって定義されます。ONTAP 9.7以前の場合は2～63日、ONTAP 9.8以降は2～183日です。



=== クラウド階層に階層化される前のデータのデフォルトのクーリング期間

コールドスナップショットポリシーのデフォルトのクーリング期間は2日間で、コールドユーザデータとスナップショットのデフォルトのクーリング期間は31日です。クーリング日数パラメータは、「すべて」の階層化ポリシーには適用されません。



=== フルバックアップを実行するときに、オブジェクトストレージから取得された階層化データはすべて取得されますか。

フルバックアップ中は、すべてのコールドデータが読み取られます。データを取得する方法は、使用する階層化ポリシーによって異なります。「すべて」と「コールドユーザデータ」と「スナップショット」のポリシーを使用している場合、コールドデータはパフォーマンス階層に書き戻されません。コールドスナップショットポリシーを使用する場合は、古いスナップショットをバックアップに使用している場合にのみコールドブロックが取得されます。



=== ボリュームあたりの階層化サイズを選択できますか。

いいえただし、階層化に適したボリューム、階層化するデータの種類、およびクーリング期間は選択できます。そのためには、ボリュームに階層化ポリシーを関連付けます。



=== 「すべてのユーザデータ」ポリシーはデータ保護ボリュームにとって唯一のオプションですか？

いいえデータ保護（DP）ボリュームは、使用可能な3つのポリシーのいずれかに関連付けることができます。データの書き込み先は、ソースボリュームとデスティネーション（DP）ボリュームで使用されるポリシーのタイプによって決まります。



=== ボリュームの階層化ポリシーを「なし」にリセットしてコールドデータを元のサイズに戻すか、将来のコールドブロックがクラウドに移動されないようにしますか？

階層化ポリシーをリセットしてもリハイドレーションは実行されませんが、新しいコールドブロックがクラウド階層に移動されないようにします。



=== データをクラウドに階層化したあとで階層化ポリシーを変更できますか。

はい。変更後の動作は、関連付けられた新しいポリシーによって異なります。



=== 特定のデータがクラウドに移動されないようにするにはどうすればよいですか？

データを含むボリュームには階層化ポリシーを関連付けないでください。



=== ファイルのメタデータはどこに保存されますか？

ボリュームのメタデータは常にローカルに、パフォーマンス階層に格納されます。クラウドに階層化されることはありません。



== ネットワークとセキュリティ

ネットワークとセキュリティに関する質問を次に示します。



=== ネットワーク要件

* ONTAP クラスタが、オブジェクトストレージプロバイダへのポート 443 経由の HTTPS 接続を開始します。
+
ONTAP は、オブジェクトストレージとの間でデータの読み取りと書き込みを行います。オブジェクトストレージが開始されることはなく、応答するだけです。

* StorageGRID の場合、 ONTAP クラスタは、ユーザ指定のポートから StorageGRID への HTTPS 接続を開始します（このポートは階層化のセットアップ時に設定可能です）。
* コネクタには、ポート 443 経由での ONTAP クラスタへのアウトバウンド HTTPS 接続、オブジェクトストア、およびクラウド階層化サービスが必要です。


詳細については、以下を参照してください。

* link:task-tiering-onprem-aws.html["Amazon S3へのデータの階層化"]
* link:task-tiering-onprem-azure.html["Azure BLOBストレージへのデータの階層化"]
* link:task-tiering-onprem-gcp.html["Google Cloud Storageへのデータの階層化"]
* link:task-tiering-onprem-storagegrid.html["データをStorageGRID に階層化する"]
* link:task-tiering-onprem-s3-compat.html["データをS3オブジェクトストレージに階層化する"]




=== クラウドに保存されたコールドデータを管理するために、監視とレポートに使用できるツールはどれですか？

Cloud Tiering以外、 https://docs.netapp.com/us-en/active-iq-unified-manager/["Active IQ Unified Manager"^] および https://docs.netapp.com/us-en/active-iq/index.html["Active IQ デジタルアドバイザ"^] 監視とレポートに使用できます。



=== クラウドプロバイダへのネットワークリンクに障害が発生した場合、どのような影響がありますか。

ネットワーク障害が発生しても、ローカルのパフォーマンス階層はオンラインのままで、ホットデータには引き続きアクセスできます。ただし、クラウド階層にすでに移動されているブロックにはアクセスできず、アプリケーションからそのデータにアクセスしようとするとエラーメッセージが表示されます。接続が回復すると、すべてのデータにシームレスにアクセスできるようになります。



=== ネットワーク帯域幅の推奨事項はありますか。

基盤となるFabricPool 階層化テクノロジの読み取りレイテンシは、クラウド階層への接続によって異なります。階層化はどの帯域幅でも機能しますが、適切なパフォーマンスを得るためには、インタークラスタLIFを10Gbpsポートに配置することを推奨します。コネクタに関する推奨事項や帯域幅の制限はありません。



=== ユーザが階層化データにアクセスしようとしたときにレイテンシは発生しますか。

はい。レイテンシは接続によって異なるため、クラウド階層と同じレイテンシを提供することはできません。オブジェクトストアのレイテンシとスループットを見積もるために、Cloud Tieringは、クラウドのパフォーマンステストを提供します（ONTAP オブジェクトストアプロファイラに基づく）。このテストは、オブジェクトストアの接続後、階層化のセットアップ前に使用できます。



=== データのセキュリティはどのようにして確保されます

パフォーマンス階層とクラウド階層の両方でAES-256-GCM暗号化が維持されます。TLS 1.2暗号化は、階層間を移動するときにネットワーク経由でデータを暗号化するため、およびコネクタとONTAP クラスタとオブジェクトストアの両方の間の通信を暗号化するために使用されます。



=== AFF にイーサネットポートをインストールして設定する必要がありますか。

はい。クラスタ間LIFは、クラウドに階層化するデータを含むボリュームをホストするHAペア内の各ノード上のイーサネットポートに設定する必要があります。詳細については、データを階層化するクラウドプロバイダの要件に関するセクションを参照してください。



=== どのような権限が必要ですか？

* link:task-tiering-onprem-aws.html#preparing-amazon-s3["Amazonの場合、S3バケットを管理するには権限が必要です"]。
* Azureでは、Cloud Managerに提供する必要のある権限以外で追加の権限は必要ありません。
* link:task-tiering-onprem-gcp.html#preparing-google-cloud-storage["Google Cloudの場合、ストレージアクセスキーを含むサービスアカウントにはストレージ管理者権限が必要です"]。
* link:task-tiering-onprem-storagegrid.html#preparing-storagegrid["StorageGRID の場合は、S3権限が必要です"]。
* link:task-tiering-onprem-s3-compat.html#preparing-s3-compatible-object-storage["S3互換オブジェクトストレージの場合は、S3権限が必要です"]。

